# Generated by Django 3.0.5 on 2020-05-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200508_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
